Betriebsysteme - myfind: myfind.c File Reference
myfind.c File Reference
#include <stdio.h>
#include <pwd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <dirent.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
Functions
void do_file (const char *file_name, const char *const *parms)
Check the given file.
void do_dir (const char *dir_name, const char *const *parms)
iterate over all files starting at current working directory
int main (int argc, const char *const argv[])
Main entry point of program.
Variables
int parms_count
Detailed Description
Main module of myfind
Author
Alexander Pirka alexa.nosp@m.nder.nosp@m..pirk.nosp@m.a@te.nosp@m.chnik.nosp@m.um-w.nosp@m.ien.a.nosp@m.t
Date
2017/02/26
Version
$Draft$
Todo:
Solve Path Problems for lstat
Stop Recursion
Find solution for passing arguments
Concept for Syscalls/library functions for actions
URL: $HeadURL$
Last Modified: $Author$
Definition in file myfind.c.
Function Documentation
void do_dir (const char * dir_name, const char *const * parms)
iterate over all files starting at current working directory
This function iterates over all files. Printf filename and passing each file of the the directory to do_find
Parameters
dir_name Name of directory. It should be called first with the current directory "."
parms Pointer to the passed arguments
Returns
None
Note
$Author$ do not know how to handle recursion and pass correct path for do_find
Definition at line 69 of file myfind.c.
References do_file().
Referenced by do_file(), and main().
void do_file (const char * file_name, const char *const * parms)
Check the given file.
This function checks the given file with lstat
Parameters
file_name Name of the file (could be directory as well)
parms Pointer to the passed arguments
Returns
None
Note
None
Definition at line 115 of file myfind.c.
References do_dir().
Referenced by do_dir().
int main (int argc, const char *const argv[])
Main entry point of program.
This function is the main entry point of the program.
Parameters
argc Number of command line arguments. (IN)
argv Array of command line arguments. (IN)
Returns
The function returns whether or not the program executed successfully.
Return values
0 Successful program termination
1 Failed program termination
Definition at line 148 of file myfind.c.
References do_dir(), and parms_count.
Variable Documentation
int parms_count
Integer number of parameters
Definition at line 45 of file myfind.c.
Referenced by main().